### ISSUE TITLE
org.fusesource.scalate.util.ClassPathBuilder fails on windows when class path entry conains *

### ISSUE THREAD

**Issue by JayChandler** [scalate/scalate#107]
I came across this problem using apache zeppelin project. The cassandra interpreter uses the scalate engine . Some how on windows i always got an IOException.

Here is the stack trace
```

java.io.IOException: Invalid argument
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
	at java.io.File.getCanonicalPath(File.java:618)
	at org.fusesource.scalate.util.ClassPathBuilder$$anonfun$getClassPathFrom$3.apply(ClassPathBuilder.scala:147)
	at org.fusesource.scalate.util.ClassPathBuilder$$anonfun$getClassPathFrom$3.apply(ClassPathBuilder.scala:142)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at org.fusesource.scalate.util.ClassPathBuilder$.getClassPathFrom(ClassPathBuilder.scala:142)
	at org.fusesource.scalate.util.ClassPathBuilder.addPathFrom(ClassPathBuilder.scala:68)
	at org.fusesource.scalate.util.ClassPathBuilder.addPathFromContextClassLoader(ClassPathBuilder.scala:73)
	at org.fusesource.scalate.support.ScalaCompiler.generateSettings(ScalaCompiler.scala:121)
	at org.fusesource.scalate.support.ScalaCompiler.<init>(ScalaCompiler.scala:59)
	at org.fusesource.scalate.support.ScalaCompiler$.create(ScalaCompiler.scala:42)
	at org.fusesource.scalate.TemplateEngine.createCompiler(TemplateEngine.scala:231)
	at org.fusesource.scalate.TemplateEngine.compiler$lzycompute(TemplateEngine.scala:221)
	at org.fusesource.scalate.TemplateEngine.compiler(TemplateEngine.scala:221)
	at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:757)
	at org.fusesource.scalate.TemplateEngine.compileAndLoadEntry(TemplateEngine.scala:699)
	at org.fusesource.scalate.TemplateEngine.liftedTree1$1(TemplateEngine.scala:419)
	at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:413)
	at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:471)
	at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:573)
	at org.apache.zeppelin.cassandra.DisplaySystem$NoResultDisplay$.<init>(DisplaySystem.scala:369)
	at org.apache.zeppelin.cassandra.DisplaySystem$NoResultDisplay$.<clinit>(DisplaySystem.scala)
	at org.apache.zeppelin.cassandra.EnhancedSession.<init>(EnhancedSession.scala:40)
	at org.apache.zeppelin.cassandra.InterpreterLogic.<init>(InterpreterLogic.scala:98)
	at org.apache.zeppelin.cassandra.CassandraInterpreter.open(CassandraInterpreter.java:231)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:70)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:491)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

I attached a remoter debugger and stepped through [this](https://github.com/scalate/scalate/blob/master/scalate-util/src/main/scala/org/fusesource/scalate/util/ClassPathBuilder.scala)

The problem is here on line [148](https://github.com/scalate/scalate/blob/master/scalate-util/src/main/scala/org/fusesource/scalate/util/ClassPathBuilder.scala#L148)

I dumped the list of class path entries `cl.getURLs.toList` and this was the output

```
0 = {URL@4550} "file:/D:/zeppelin/bin/"
1 = {URL@4551} "file:/D:/zeppelin/interpreter/cassandra/cassandra-driver-core-3.0.1.jar"
2 = {URL@4552} "file:/D:/zeppelin/interpreter/cassandra/commons-lang3-3.3.2.jar"
3 = {URL@4553} "file:/D:/zeppelin/interpreter/cassandra/guava-16.0.1.jar"
4 = {URL@4554} "file:/D:/zeppelin/interpreter/cassandra/lz4-1.3.0.jar"
5 = {URL@4555} "file:/D:/zeppelin/interpreter/cassandra/metrics-core-3.1.2.jar"
6 = {URL@4556} "file:/D:/zeppelin/interpreter/cassandra/netty-buffer-4.0.33.Final.jar"
7 = {URL@4557} "file:/D:/zeppelin/interpreter/cassandra/netty-codec-4.0.33.Final.jar"
8 = {URL@4558} "file:/D:/zeppelin/interpreter/cassandra/netty-common-4.0.33.Final.jar"
9 = {URL@4559} "file:/D:/zeppelin/interpreter/cassandra/netty-handler-4.0.33.Final.jar"
10 = {URL@4560} "file:/D:/zeppelin/interpreter/cassandra/netty-transport-4.0.33.Final.jar"
11 = {URL@4561} "file:/D:/zeppelin/interpreter/cassandra/scala-compiler-2.11.7.jar"
12 = {URL@4562} "file:/D:/zeppelin/interpreter/cassandra/scala-library-2.11.7.jar"
13 = {URL@4563} "file:/D:/zeppelin/interpreter/cassandra/scala-parser-combinators_2.11-1.0.4.jar"
14 = {URL@4564} "file:/D:/zeppelin/interpreter/cassandra/scala-reflect-2.11.7.jar"
15 = {URL@4565} "file:/D:/zeppelin/interpreter/cassandra/scala-xml_2.11-1.0.4.jar"
16 = {URL@4566} "file:/D:/zeppelin/interpreter/cassandra/scalate-core_2.11-1.7.1.jar"
17 = {URL@4567} "file:/D:/zeppelin/interpreter/cassandra/scalate-util_2.11-1.7.1.jar"
18 = {URL@4568} "file:/D:/zeppelin/interpreter/cassandra/slf4j-api-1.7.10.jar"
19 = {URL@4569} "file:/D:/zeppelin/interpreter/cassandra/snappy-java-1.0.5.4.jar"
20 = {URL@4570} "file:/D:/zeppelin/interpreter/cassandra/zeppelin-cassandra_2.11-0.7.3.jar"
21 = {URL@4571} "file:/D:/zeppelin/lib/interpreter/aether-api-1.12.jar"
22 = {URL@4572} "file:/D:/zeppelin/lib/interpreter/aether-connector-file-1.12.jar"
23 = {URL@4573} "file:/D:/zeppelin/lib/interpreter/aether-connector-wagon-1.12.jar"
24 = {URL@4574} "file:/D:/zeppelin/lib/interpreter/aether-impl-1.12.jar"
25 = {URL@4575} "file:/D:/zeppelin/lib/interpreter/aether-spi-1.12.jar"
26 = {URL@4576} "file:/D:/zeppelin/lib/interpreter/aether-util-1.12.jar"
27 = {URL@4577} "file:/D:/zeppelin/lib/interpreter/commons-codec-1.5.jar"
28 = {URL@4578} "file:/D:/zeppelin/lib/interpreter/commons-exec-1.3.jar"
29 = {URL@4579} "file:/D:/zeppelin/lib/interpreter/commons-httpclient-3.1.jar"
30 = {URL@4580} "file:/D:/zeppelin/lib/interpreter/commons-io-2.4.jar"
31 = {URL@4581} "file:/D:/zeppelin/lib/interpreter/commons-lang-2.5.jar"
32 = {URL@4582} "file:/D:/zeppelin/lib/interpreter/commons-logging-1.1.1.jar"
33 = {URL@4583} "file:/D:/zeppelin/lib/interpreter/commons-pool2-2.3.jar"
34 = {URL@4584} "file:/D:/zeppelin/lib/interpreter/gson-2.2.jar"
35 = {URL@4585} "file:/D:/zeppelin/lib/interpreter/httpclient-4.5.1.jar"
36 = {URL@4586} "file:/D:/zeppelin/lib/interpreter/httpcore-4.4.1.jar"
37 = {URL@4587} "file:/D:/zeppelin/lib/interpreter/jsoup-1.6.1.jar"
38 = {URL@4588} "file:/D:/zeppelin/lib/interpreter/libthrift-0.9.2.jar"
39 = {URL@4589} "file:/D:/zeppelin/lib/interpreter/log4j-1.2.17.jar"
40 = {URL@4590} "file:/D:/zeppelin/lib/interpreter/maven-aether-provider-3.0.3.jar"
41 = {URL@4591} "file:/D:/zeppelin/lib/interpreter/maven-artifact-3.0.jar"
42 = {URL@4592} "file:/D:/zeppelin/lib/interpreter/maven-model-3.0.3.jar"
43 = {URL@4593} "file:/D:/zeppelin/lib/interpreter/maven-model-builder-3.0.3.jar"
44 = {URL@4594} "file:/D:/zeppelin/lib/interpreter/maven-plugin-api-3.0.jar"
45 = {URL@4595} "file:/D:/zeppelin/lib/interpreter/maven-repository-metadata-3.0.3.jar"
46 = {URL@4596} "file:/D:/zeppelin/lib/interpreter/plexus-classworlds-2.4.jar"
47 = {URL@4597} "file:/D:/zeppelin/lib/interpreter/plexus-component-annotations-1.5.5.jar"
48 = {URL@4598} "file:/D:/zeppelin/lib/interpreter/plexus-interpolation-1.14.jar"
49 = {URL@4599} "file:/D:/zeppelin/lib/interpreter/plexus-utils-2.0.7.jar"
50 = {URL@4600} "file:/D:/zeppelin/lib/interpreter/sisu-guice-3.0.2-no_aop.jar"
51 = {URL@4601} "file:/D:/zeppelin/lib/interpreter/sisu-inject-bean-2.2.2.jar"
52 = {URL@4602} "file:/D:/zeppelin/lib/interpreter/sisu-inject-plexus-2.2.2.jar"
53 = {URL@4603} "file:/D:/zeppelin/lib/interpreter/slf4j-api-1.7.10.jar"
54 = {URL@4604} "file:/D:/zeppelin/lib/interpreter/slf4j-log4j12-1.7.10.jar"
55 = {URL@4605} "file:/D:/zeppelin/lib/interpreter/wagon-http-1.0.jar"
56 = {URL@4606} "file:/D:/zeppelin/lib/interpreter/wagon-http-lightweight-1.0.jar"
57 = {URL@4607} "file:/D:/zeppelin/lib/interpreter/wagon-http-shared-1.0.jar"
58 = {URL@4608} "file:/D:/zeppelin/lib/interpreter/wagon-provider-api-1.0.jar"
59 = {URL@4609} "file:/D:/zeppelin/lib/interpreter/zeppelin-interpreter-0.7.3.jar"
60 = {URL@4610} "file:/D:/zeppelin/lib/interpreter/aether-api-1.12.jar"
61 = {URL@4611} "file:/D:/zeppelin/lib/interpreter/aether-connector-file-1.12.jar"
62 = {URL@4612} "file:/D:/zeppelin/lib/interpreter/aether-connector-wagon-1.12.jar"
63 = {URL@4613} "file:/D:/zeppelin/lib/interpreter/aether-impl-1.12.jar"
64 = {URL@4614} "file:/D:/zeppelin/lib/interpreter/aether-spi-1.12.jar"
65 = {URL@4615} "file:/D:/zeppelin/lib/interpreter/aether-util-1.12.jar"
66 = {URL@4616} "file:/D:/zeppelin/lib/interpreter/commons-codec-1.5.jar"
67 = {URL@4617} "file:/D:/zeppelin/lib/interpreter/commons-exec-1.3.jar"
68 = {URL@4618} "file:/D:/zeppelin/lib/interpreter/commons-httpclient-3.1.jar"
69 = {URL@4619} "file:/D:/zeppelin/lib/interpreter/commons-io-2.4.jar"
70 = {URL@4620} "file:/D:/zeppelin/lib/interpreter/commons-lang-2.5.jar"
71 = {URL@4621} "file:/D:/zeppelin/lib/interpreter/commons-logging-1.1.1.jar"
72 = {URL@4622} "file:/D:/zeppelin/lib/interpreter/commons-pool2-2.3.jar"
73 = {URL@4623} "file:/D:/zeppelin/lib/interpreter/gson-2.2.jar"
74 = {URL@4624} "file:/D:/zeppelin/lib/interpreter/httpclient-4.5.1.jar"
75 = {URL@4625} "file:/D:/zeppelin/lib/interpreter/httpcore-4.4.1.jar"
76 = {URL@4626} "file:/D:/zeppelin/lib/interpreter/jsoup-1.6.1.jar"
77 = {URL@4627} "file:/D:/zeppelin/lib/interpreter/libthrift-0.9.2.jar"
78 = {URL@4628} "file:/D:/zeppelin/lib/interpreter/log4j-1.2.17.jar"
79 = {URL@4629} "file:/D:/zeppelin/lib/interpreter/maven-aether-provider-3.0.3.jar"
80 = {URL@4630} "file:/D:/zeppelin/lib/interpreter/maven-artifact-3.0.jar"
81 = {URL@4631} "file:/D:/zeppelin/lib/interpreter/maven-model-3.0.3.jar"
82 = {URL@4632} "file:/D:/zeppelin/lib/interpreter/maven-model-builder-3.0.3.jar"
83 = {URL@4633} "file:/D:/zeppelin/lib/interpreter/maven-plugin-api-3.0.jar"
84 = {URL@4634} "file:/D:/zeppelin/lib/interpreter/maven-repository-metadata-3.0.3.jar"
85 = {URL@4635} "file:/D:/zeppelin/lib/interpreter/plexus-classworlds-2.4.jar"
86 = {URL@4636} "file:/D:/zeppelin/lib/interpreter/plexus-component-annotations-1.5.5.jar"
87 = {URL@4637} "file:/D:/zeppelin/lib/interpreter/plexus-interpolation-1.14.jar"
88 = {URL@4638} "file:/D:/zeppelin/lib/interpreter/plexus-utils-2.0.7.jar"
89 = {URL@4639} "file:/D:/zeppelin/lib/interpreter/sisu-guice-3.0.2-no_aop.jar"
90 = {URL@4640} "file:/D:/zeppelin/lib/interpreter/sisu-inject-bean-2.2.2.jar"
91 = {URL@4641} "file:/D:/zeppelin/lib/interpreter/sisu-inject-plexus-2.2.2.jar"
92 = {URL@4642} "file:/D:/zeppelin/lib/interpreter/slf4j-api-1.7.10.jar"
93 = {URL@4643} "file:/D:/zeppelin/lib/interpreter/slf4j-log4j12-1.7.10.jar"
94 = {URL@4644} "file:/D:/zeppelin/lib/interpreter/wagon-http-1.0.jar"
95 = {URL@4645} "file:/D:/zeppelin/lib/interpreter/wagon-http-lightweight-1.0.jar"
96 = {URL@4646} "file:/D:/zeppelin/lib/interpreter/wagon-http-shared-1.0.jar"
97 = {URL@4647} "file:/D:/zeppelin/lib/interpreter/wagon-provider-api-1.0.jar"
98 = {URL@4648} "file:/D:/zeppelin/lib/interpreter/zeppelin-interpreter-0.7.3.jar"
99 = {URL@4649} "file:/D:/zeppelin/lib/apacheds-i18n-2.0.0-M15.jar"
100 = {URL@4751} "file:/D:/zeppelin/lib/apacheds-kerberos-codec-2.0.0-M15.jar"
101 = {URL@4752} "file:/D:/zeppelin/lib/api-asn1-api-1.0.0-M20.jar"
102 = {URL@4753} "file:/D:/zeppelin/lib/api-util-1.0.0-M20.jar"
103 = {URL@4754} "file:/D:/zeppelin/lib/asm-3.1.jar"
104 = {URL@4755} "file:/D:/zeppelin/lib/aws-java-sdk-core-1.10.62.jar"
105 = {URL@4756} "file:/D:/zeppelin/lib/aws-java-sdk-kms-1.10.62.jar"
106 = {URL@4757} "file:/D:/zeppelin/lib/aws-java-sdk-s3-1.10.62.jar"
107 = {URL@4758} "file:/D:/zeppelin/lib/azure-storage-4.0.0.jar"
108 = {URL@4759} "file:/D:/zeppelin/lib/c3p0-0.9.1.1.jar"
109 = {URL@4760} "file:/D:/zeppelin/lib/commons-beanutils-1.8.3.jar"
110 = {URL@4761} "file:/D:/zeppelin/lib/commons-cli-1.2.jar"
111 = {URL@4762} "file:/D:/zeppelin/lib/commons-codec-1.5.jar"
112 = {URL@4763} "file:/D:/zeppelin/lib/commons-collections-3.2.1.jar"
113 = {URL@4764} "file:/D:/zeppelin/lib/commons-compress-1.5.jar"
114 = {URL@4765} "file:/D:/zeppelin/lib/commons-configuration-1.9.jar"
115 = {URL@4766} "file:/D:/zeppelin/lib/commons-el-1.0.jar"
116 = {URL@4767} "file:/D:/zeppelin/lib/commons-io-2.4.jar"
117 = {URL@4768} "file:/D:/zeppelin/lib/commons-lang-2.5.jar"
118 = {URL@4769} "file:/D:/zeppelin/lib/commons-lang3-3.4.jar"
119 = {URL@4770} "file:/D:/zeppelin/lib/commons-logging-1.1.1.jar"
120 = {URL@4771} "file:/D:/zeppelin/lib/commons-math3-3.1.1.jar"
121 = {URL@4772} "file:/D:/zeppelin/lib/commons-net-3.1.jar"
122 = {URL@4773} "file:/D:/zeppelin/lib/commons-vfs2-2.0.jar"
123 = {URL@4774} "file:/D:/zeppelin/lib/curator-client-2.6.0.jar"
124 = {URL@4775} "file:/D:/zeppelin/lib/curator-framework-2.6.0.jar"
125 = {URL@4776} "file:/D:/zeppelin/lib/curator-recipes-2.6.0.jar"
126 = {URL@4777} "file:/D:/zeppelin/lib/cxf-api-2.7.8.jar"
127 = {URL@4778} "file:/D:/zeppelin/lib/cxf-rt-bindings-xml-2.7.8.jar"
128 = {URL@4779} "file:/D:/zeppelin/lib/cxf-rt-core-2.7.8.jar"
129 = {URL@4780} "file:/D:/zeppelin/lib/cxf-rt-frontend-jaxrs-2.7.8.jar"
130 = {URL@4781} "file:/D:/zeppelin/lib/cxf-rt-transports-http-2.7.8.jar"
131 = {URL@4782} "file:/D:/zeppelin/lib/cxf-rt-transports-http-jetty-2.7.8.jar"
132 = {URL@4783} "file:/D:/zeppelin/lib/dom4j-1.6.1.jar"
133 = {URL@4784} "file:/D:/zeppelin/lib/frontend-maven-plugin-1.3.jar"
134 = {URL@4785} "file:/D:/zeppelin/lib/frontend-plugin-core-1.3.jar"
135 = {URL@4786} "file:/D:/zeppelin/lib/geronimo-javamail_1.4_spec-1.7.1.jar"
136 = {URL@4787} "file:/D:/zeppelin/lib/geronimo-servlet_3.0_spec-1.0.jar"
137 = {URL@4788} "file:/D:/zeppelin/lib/gson-2.2.jar"
138 = {URL@4789} "file:/D:/zeppelin/lib/guava-15.0.jar"
139 = {URL@4790} "file:/D:/zeppelin/lib/hadoop-annotations-2.6.0.jar"
140 = {URL@4791} "file:/D:/zeppelin/lib/hadoop-auth-2.6.0.jar"
141 = {URL@4792} "file:/D:/zeppelin/lib/hadoop-common-2.6.0.jar"
142 = {URL@4793} "file:/D:/zeppelin/lib/htrace-core-3.0.4.jar"
143 = {URL@4794} "file:/D:/zeppelin/lib/httpasyncclient-4.0.2.jar"
144 = {URL@4795} "file:/D:/zeppelin/lib/httpclient-4.5.1.jar"
145 = {URL@4796} "file:/D:/zeppelin/lib/httpcore-4.4.1.jar"
146 = {URL@4797} "file:/D:/zeppelin/lib/httpcore-nio-4.3.2.jar"
147 = {URL@4798} "file:/D:/zeppelin/lib/jackrabbit-jcr-commons-1.5.2.jar"
148 = {URL@4799} "file:/D:/zeppelin/lib/jackrabbit-webdav-1.5.2.jar"
149 = {URL@4800} "file:/D:/zeppelin/lib/jackson-annotations-2.5.0.jar"
150 = {URL@4801} "file:/D:/zeppelin/lib/jackson-core-2.5.3.jar"
151 = {URL@4802} "file:/D:/zeppelin/lib/jackson-core-asl-1.9.13.jar"
152 = {URL@4803} "file:/D:/zeppelin/lib/jackson-databind-2.5.3.jar"
153 = {URL@4804} "file:/D:/zeppelin/lib/jackson-mapper-asl-1.9.13.jar"
154 = {URL@4805} "file:/D:/zeppelin/lib/jasper-compiler-5.5.23.jar"
155 = {URL@4806} "file:/D:/zeppelin/lib/jasper-runtime-5.5.23.jar"
156 = {URL@4807} "file:/D:/zeppelin/lib/java-xmlbuilder-0.4.jar"
157 = {URL@4808} "file:/D:/zeppelin/lib/JavaEWAH-0.7.9.jar"
158 = {URL@4809} "file:/D:/zeppelin/lib/javassist-3.12.1.GA.jar"
159 = {URL@4810} "file:/D:/zeppelin/lib/javax.servlet-api-3.1.0.jar"
160 = {URL@4811} "file:/D:/zeppelin/lib/javax.ws.rs-api-2.0-m10.jar"
161 = {URL@4812} "file:/D:/zeppelin/lib/jaxb-impl-2.2.6.jar"
162 = {URL@4813} "file:/D:/zeppelin/lib/jersey-core-1.13.jar"
163 = {URL@4814} "file:/D:/zeppelin/lib/jersey-server-1.13.jar"
164 = {URL@4815} "file:/D:/zeppelin/lib/jersey-servlet-1.13.jar"
165 = {URL@4816} "file:/D:/zeppelin/lib/jets3t-0.9.0.jar"
166 = {URL@4817} "file:/D:/zeppelin/lib/jetty-6.1.26.jar"
167 = {URL@4818} "file:/D:/zeppelin/lib/jetty-client-9.2.15.v20160210.jar"
168 = {URL@4819} "file:/D:/zeppelin/lib/jetty-http-9.2.15.v20160210.jar"
169 = {URL@4820} "file:/D:/zeppelin/lib/jetty-io-9.2.15.v20160210.jar"
170 = {URL@4821} "file:/D:/zeppelin/lib/jetty-security-9.2.15.v20160210.jar"
171 = {URL@4822} "file:/D:/zeppelin/lib/jetty-server-9.2.15.v20160210.jar"
172 = {URL@4823} "file:/D:/zeppelin/lib/jetty-servlet-9.2.15.v20160210.jar"
173 = {URL@4824} "file:/D:/zeppelin/lib/jetty-util-6.1.26.jar"
174 = {URL@4825} "file:/D:/zeppelin/lib/jetty-util-9.2.15.v20160210.jar"
175 = {URL@4826} "file:/D:/zeppelin/lib/jetty-webapp-9.2.15.v20160210.jar"
176 = {URL@4827} "file:/D:/zeppelin/lib/jetty-xml-9.2.15.v20160210.jar"
177 = {URL@4828} "file:/D:/zeppelin/lib/jna-4.1.0.jar"
178 = {URL@4829} "file:/D:/zeppelin/lib/joda-time-2.8.1.jar"
179 = {URL@4830} "file:/D:/zeppelin/lib/jsch-0.1.53.jar"
180 = {URL@4831} "file:/D:/zeppelin/lib/jsp-api-2.1.jar"
181 = {URL@4832} "file:/D:/zeppelin/lib/jsr305-1.3.9.jar"
182 = {URL@4833} "file:/D:/zeppelin/lib/libpam4j-1.8.jar"
183 = {URL@4834} "file:/D:/zeppelin/lib/log4j-1.2.17.jar"
184 = {URL@4835} "file:/D:/zeppelin/lib/lucene-analyzers-common-5.3.1.jar"
185 = {URL@4836} "file:/D:/zeppelin/lib/lucene-core-5.3.1.jar"
186 = {URL@4837} "file:/D:/zeppelin/lib/lucene-highlighter-5.3.1.jar"
187 = {URL@4838} "file:/D:/zeppelin/lib/lucene-join-5.3.1.jar"
188 = {URL@4839} "file:/D:/zeppelin/lib/lucene-memory-5.3.1.jar"
189 = {URL@4840} "file:/D:/zeppelin/lib/lucene-queries-5.3.1.jar"
190 = {URL@4841} "file:/D:/zeppelin/lib/lucene-queryparser-5.3.1.jar"
191 = {URL@4842} "file:/D:/zeppelin/lib/lucene-sandbox-5.3.1.jar"
192 = {URL@4843} "file:/D:/zeppelin/lib/maven-plugin-annotations-3.2.jar"
193 = {URL@4844} "file:/D:/zeppelin/lib/maven-scm-api-1.4.jar"
194 = {URL@4845} "file:/D:/zeppelin/lib/maven-scm-provider-svn-commons-1.4.jar"
195 = {URL@4846} "file:/D:/zeppelin/lib/maven-scm-provider-svnexe-1.4.jar"
196 = {URL@4847} "file:/D:/zeppelin/lib/org.eclipse.jdt.annotation-1.1.0.jar"
197 = {URL@4848} "file:/D:/zeppelin/lib/org.eclipse.jgit-4.1.1.201511131810-r.jar"
198 = {URL@4849} "file:/D:/zeppelin/lib/plexus-build-api-0.0.7.jar"
199 = {URL@4850} "file:/D:/zeppelin/lib/protobuf-java-2.5.0.jar"
200 = {URL@4953} "file:/D:/zeppelin/lib/quartz-2.2.1.jar"
201 = {URL@4954} "file:/D:/zeppelin/lib/reflections-0.9.8.jar"
202 = {URL@4955} "file:/D:/zeppelin/lib/regexp-1.3.jar"
203 = {URL@4956} "file:/D:/zeppelin/lib/scala-compiler-2.11.7.jar"
204 = {URL@4957} "file:/D:/zeppelin/lib/scala-library-2.11.7.jar"
205 = {URL@4958} "file:/D:/zeppelin/lib/scala-parser-combinators_2.11-1.0.4.jar"
206 = {URL@4959} "file:/D:/zeppelin/lib/scala-reflect-2.11.7.jar"
207 = {URL@4960} "file:/D:/zeppelin/lib/scala-xml_2.11-1.0.2.jar"
208 = {URL@4961} "file:/D:/zeppelin/lib/shiro-core-1.2.3.jar"
209 = {URL@4962} "file:/D:/zeppelin/lib/shiro-web-1.2.3.jar"
210 = {URL@4963} "file:/D:/zeppelin/lib/slf4j-api-1.7.10.jar"
211 = {URL@4964} "file:/D:/zeppelin/lib/slf4j-log4j12-1.7.10.jar"
212 = {URL@4965} "file:/D:/zeppelin/lib/stax2-api-3.1.1.jar"
213 = {URL@4966} "file:/D:/zeppelin/lib/websocket-api-9.2.15.v20160210.jar"
214 = {URL@4967} "file:/D:/zeppelin/lib/websocket-client-9.2.15.v20160210.jar"
215 = {URL@4968} "file:/D:/zeppelin/lib/websocket-common-9.2.15.v20160210.jar"
216 = {URL@4969} "file:/D:/zeppelin/lib/websocket-server-9.2.15.v20160210.jar"
217 = {URL@4970} "file:/D:/zeppelin/lib/websocket-servlet-9.2.15.v20160210.jar"
218 = {URL@4971} "file:/D:/zeppelin/lib/woodstox-core-asl-4.2.0.jar"
219 = {URL@4972} "file:/D:/zeppelin/lib/wsdl4j-1.6.3.jar"
220 = {URL@4973} "file:/D:/zeppelin/lib/xml-apis-1.4.01.jar"
221 = {URL@4974} "file:/D:/zeppelin/lib/xmlenc-0.52.jar"
222 = {URL@4975} "file:/D:/zeppelin/lib/xmlschema-core-2.0.3.jar"
223 = {URL@4976} "file:/D:/zeppelin/lib/xz-1.2.jar"
224 = {URL@4977} "file:/D:/zeppelin/lib/zeppelin-server-0.7.3.jar"
225 = {URL@4978} "file:/D:/zeppelin/lib/zeppelin-zengine-0.7.3.jar"
226 = {URL@4979} "file:/D:/zeppelin/*"
227 = {URL@4980} "file:/D:/zeppelin/conf/"
228 = {URL@4981} "file:/D:/zeppelin/conf/"
```

The problem is this line

**226 = {URL@4979} "file:/D:/zeppelin/*"**

It throws an `java.io.IOException: Invalid argument` on Windows. On linux it just works fine. Seems thats a windows related problem. How can this be fixed?

As far as i know wildcards are allowed in class path entries. Aren't they ?

Thx

**Comment by jvr-ks** [comment]
https://en.wikipedia.org/wiki/File_URI_scheme
