### ISSUE TITLE
JDK11 not compatible to "org.scalatra.scalate:scalate-core_2.11:1.9.6" ?

### ISSUE THREAD

**Issue by dr-lab** [scalate/scalate#275]
When run in JDK11 , see bunch of bellow error when using _2.11:1.9.6?  Seems like the lib is compiled by JDK8 ?

org.fusesource.scalate.TemplateException: Not a version: 9
  at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:761)
  at org.fusesource.scalate.TemplateEngine.compile(TemplateEngine.scala:339)
  at org.fusesource.scalate.TemplateEngine.compileText(TemplateEngine.scala:331)
  at com.apple.amp.ae.fact.wpc.report.te.ContentGenerator$ContentGenerator.fromText(ContentGenerator.scala:58

```
Cause: java.lang.NumberFormatException: Not a version: 9
  at scala.util.PropertiesTrait$class.parts$1(Properties.scala:184)
  at scala.util.PropertiesTrait$class.isJavaAtLeast(Properties.scala:187)
  at scala.util.Properties$.isJavaAtLeast(Properties.scala:17)
  at scala.tools.util.PathResolverBase$Calculated$.javaBootClasspath(PathResolver.scala:276)
  at scala.tools.util.PathResolverBase$Calculated$.basis(PathResolver.scala:283)
  at scala.tools.util.PathResolverBase$Calculated$.containers$lzycompute(PathResolver.scala:293)
  at scala.tools.util.PathResolverBase$Calculated$.containers(PathResolver.scala:293)
  at scala.tools.util.PathResolverBase.containers(PathResolver.scala:309)
  at scala.tools.util.PathResolver.computeResult(PathResolver.scala:341)
  at scala.tools.util.PathResolver.computeResult(PathResolver.scala:332)
  ...
```

**Comment by xuwei-k** [comment]
I think this is not scalate issue.
https://github.com/scala/scala/commit/0259b94219c27856552c7ef00a620451c7a4
please update your scala version.
