### ISSUE TITLE
java.lang.ClassCastException: org.fusesource.scalate.filter.ScalaMarkdownFilter$ cannot be cast to org.fusesource.scalate.TemplateEngineAddOn

### ISSUE THREAD

**Issue by simao** [scalate/scalate#81]
I am using the following code to initialize a TemplateEngine:

```
val buffer = new StringWriter()
val out = new PrintWriter(buffer)
val t = new TemplateEngine
```

But I am getting this exception:

```
java.lang.ClassCastException: org.fusesource.scalate.filter.ScalaMarkdownFilter$ cannot be cast to org.fusesource.scalate.TemplateEngineAddOn
	at org.fusesource.scalate.TemplateEngine$$anonfun$8.apply(TemplateEngine.scala:261)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.fusesource.scalate.TemplateEngine.<init>(TemplateEngine.scala:261)

```

Is this a known issue?

Thank you

**Comment by PlenipotentSS** [comment]
Bringing this back, our use case also found this issue and it seems to be due to how ScalaMarkdownFilter is being loaded and possible issues around multithreaded environments. Currently, we have lots of unit tests across different templates using scalate and we get the same exact issue. We were able to baseline out of 10 tests, with ~10s of unit tests failing due to the same issue @simao mentioned.

Currently, the working code that resolved the issue is to remove the reflection loading and maintain the "attempt" process to load the template engine. See: https://github.com/PlenipotentSS/scalate/commit/564dccc2d2f87d9f05d4312104c53eb3bfff6879

I also suggest that we clean up the use of the reflection here as it can cause lots of issues in larger environments. Open to any discussion.

**Comment by PlenipotentSS** [comment]
I think this issue can be closed since there was an issue with class loading found here: https://github.com/scalate/scalate/commit/21f94b9fab956d7566cc4213f85820118b3953e3 . @magnolia-k Do you have any plans to add minor versions to update the few tags that can use this? Namely, I have a project that runs scalate-util version 1.9.6 that we would like to maintain until we do a later scalatra update.

**Comment by magnolia-k** [comment]
@seratch 

Could you please release a new version?

**Comment by seratch** [comment]
@magnolia-k I haven't actively working on this project anymore. Is it possible to ask you to do the release for me? If you don't have the permission, you can create your own sonatype account and create a new JIRA ticket to add you to the groupId (org.scalatra). Please refer to [this ticket](https://issues.sonatype.org/browse/OSSRH-39113) for more details. Perhaps, you need to make your membership [here](https://github.com/orgs/scalate/people) public before creating the JIRA ticket.
